//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.12 at 01:59:25 PM ICT 
//


package com.kmutt.sit.pegasus.xsd.element;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="filename" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"&gt;
 *                 &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" /&gt;
 *                 &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="job" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="argument" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                             &lt;element name="filename" type="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="profile" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                             &lt;element name="filename" type="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="namespace" use="required" type="{http://pegasus.isi.edu/schema/DAX}ProfileNamespace" /&gt;
 *                           &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" default="vdl" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="stdin" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
 *                           &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="input" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="stdout" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
 *                           &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="output" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="stderr" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
 *                           &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="output" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="uses" type="{http://pegasus.isi.edu/schema/DAX}FilenameType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="dv-namespace" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="dv-name" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *                 &lt;attribute name="dv-version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *                 &lt;attribute name="runtime" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *                 &lt;attribute name="compound" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="child" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded"&gt;
 *                   &lt;element name="parent"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;pattern value="[0-9]+\.[0-9]+[a-z]?"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="jobCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="fileCount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="childCount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filename",
    "job",
    "child"
})
@XmlRootElement(name = "adag")
public class Adag {

    protected List<Adag.Filename> filename;
    @XmlElement(required = true)
    protected List<Adag.Job> job;
    protected List<Adag.Child> child;
    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "index", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger index;
    @XmlAttribute(name = "count", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger count;
    @XmlAttribute(name = "jobCount")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger jobCount;
    @XmlAttribute(name = "fileCount")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger fileCount;
    @XmlAttribute(name = "childCount")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger childCount;

    /**
     * Gets the value of the filename property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filename property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilename().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Adag.Filename }
     * 
     * 
     */
    public List<Adag.Filename> getFilename() {
        if (filename == null) {
            filename = new ArrayList<Adag.Filename>();
        }
        return this.filename;
    }

    /**
     * Gets the value of the job property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the job property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJob().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Adag.Job }
     * 
     * 
     */
    public List<Adag.Job> getJob() {
        if (job == null) {
            job = new ArrayList<Adag.Job>();
        }
        return this.job;
    }

    /**
     * Gets the value of the child property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the child property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChild().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Adag.Child }
     * 
     * 
     */
    public List<Adag.Child> getChild() {
        if (child == null) {
            child = new ArrayList<Adag.Child>();
        }
        return this.child;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the jobCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJobCount() {
        return jobCount;
    }

    /**
     * Sets the value of the jobCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJobCount(BigInteger value) {
        this.jobCount = value;
    }

    /**
     * Gets the value of the fileCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFileCount() {
        return fileCount;
    }

    /**
     * Sets the value of the fileCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFileCount(BigInteger value) {
        this.fileCount = value;
    }

    /**
     * Gets the value of the childCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChildCount() {
        return childCount;
    }

    /**
     * Sets the value of the childCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChildCount(BigInteger value) {
        this.childCount = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded"&gt;
     *         &lt;element name="parent"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parent"
    })
    public static class Child {

        @XmlElement(required = true)
        protected List<Adag.Child.Parent> parent;
        @XmlAttribute(name = "ref", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Adag.Job ref;

        /**
         * Gets the value of the parent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Adag.Child.Parent }
         * 
         * 
         */
        public List<Adag.Child.Parent> getParent() {
            if (parent == null) {
                parent = new ArrayList<Adag.Child.Parent>();
            }
            return this.parent;
        }

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link Adag.Job }
         *     
         */
        public Adag.Job getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adag.Job }
         *     
         */
        public void setRef(Adag.Job value) {
            this.ref = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Parent {

            @XmlAttribute(name = "ref", required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Adag.Job ref;

            /**
             * Gets the value of the ref property.
             * 
             * @return
             *     possible object is
             *     {@link Adag.Job }
             *     
             */
            public Adag.Job getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             * 
             * @param value
             *     allowed object is
             *     {@link Adag.Job }
             *     
             */
            public void setRef(Adag.Job value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"&gt;
     *       &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" /&gt;
     *       &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Filename
        extends PlainFilenameType
    {

        @XmlAttribute(name = "link")
        protected LinkageType link;
        @XmlAttribute(name = "optional")
        protected Boolean optional;

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link LinkageType }
         *     
         */
        public LinkageType getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link LinkageType }
         *     
         */
        public void setLink(LinkageType value) {
            this.link = value;
        }

        /**
         * Gets the value of the optional property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOptional() {
            if (optional == null) {
                return false;
            } else {
                return optional;
            }
        }

        /**
         * Sets the value of the optional property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOptional(Boolean value) {
            this.optional = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="argument" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *                   &lt;element name="filename" type="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="profile" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *                   &lt;element name="filename" type="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="namespace" use="required" type="{http://pegasus.isi.edu/schema/DAX}ProfileNamespace" /&gt;
     *                 &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" default="vdl" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="stdin" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
     *                 &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="input" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="stdout" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
     *                 &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="output" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="stderr" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
     *                 &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="output" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="uses" type="{http://pegasus.isi.edu/schema/DAX}FilenameType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="dv-namespace" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="dv-name" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
     *       &lt;attribute name="dv-version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
     *       &lt;attribute name="runtime" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
     *       &lt;attribute name="compound" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "argument",
        "profile",
        "stdin",
        "stdout",
        "stderr",
        "uses"
    })
    public static class Job {

        protected Adag.Job.Argument argument;
        protected List<Adag.Job.Profile> profile;
        protected Adag.Job.Stdin stdin;
        protected Adag.Job.Stdout stdout;
        protected Adag.Job.Stderr stderr;
        protected List<FilenameType> uses;
        @XmlAttribute(name = "namespace")
        protected String namespace;
        @XmlAttribute(name = "name", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NMTOKEN")
        protected String name;
        @XmlAttribute(name = "version")
        protected String version;
        @XmlAttribute(name = "dv-namespace")
        protected String dvNamespace;
        @XmlAttribute(name = "dv-name")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NMTOKEN")
        protected String dvName;
        @XmlAttribute(name = "dv-version")
        protected String dvVersion;
        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "runtime")
        protected BigDecimal runtime;
        @XmlAttribute(name = "level")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger level;
        @XmlAttribute(name = "compound")
        @XmlSchemaType(name = "NMTOKENS")
        protected List<String> compound;

        /**
         * Gets the value of the argument property.
         * 
         * @return
         *     possible object is
         *     {@link Adag.Job.Argument }
         *     
         */
        public Adag.Job.Argument getArgument() {
            return argument;
        }

        /**
         * Sets the value of the argument property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adag.Job.Argument }
         *     
         */
        public void setArgument(Adag.Job.Argument value) {
            this.argument = value;
        }

        /**
         * Gets the value of the profile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the profile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Adag.Job.Profile }
         * 
         * 
         */
        public List<Adag.Job.Profile> getProfile() {
            if (profile == null) {
                profile = new ArrayList<Adag.Job.Profile>();
            }
            return this.profile;
        }

        /**
         * Gets the value of the stdin property.
         * 
         * @return
         *     possible object is
         *     {@link Adag.Job.Stdin }
         *     
         */
        public Adag.Job.Stdin getStdin() {
            return stdin;
        }

        /**
         * Sets the value of the stdin property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adag.Job.Stdin }
         *     
         */
        public void setStdin(Adag.Job.Stdin value) {
            this.stdin = value;
        }

        /**
         * Gets the value of the stdout property.
         * 
         * @return
         *     possible object is
         *     {@link Adag.Job.Stdout }
         *     
         */
        public Adag.Job.Stdout getStdout() {
            return stdout;
        }

        /**
         * Sets the value of the stdout property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adag.Job.Stdout }
         *     
         */
        public void setStdout(Adag.Job.Stdout value) {
            this.stdout = value;
        }

        /**
         * Gets the value of the stderr property.
         * 
         * @return
         *     possible object is
         *     {@link Adag.Job.Stderr }
         *     
         */
        public Adag.Job.Stderr getStderr() {
            return stderr;
        }

        /**
         * Sets the value of the stderr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adag.Job.Stderr }
         *     
         */
        public void setStderr(Adag.Job.Stderr value) {
            this.stderr = value;
        }

        /**
         * Gets the value of the uses property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uses property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUses().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FilenameType }
         * 
         * 
         */
        public List<FilenameType> getUses() {
            if (uses == null) {
                uses = new ArrayList<FilenameType>();
            }
            return this.uses;
        }

        /**
         * Gets the value of the namespace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNamespace() {
            return namespace;
        }

        /**
         * Sets the value of the namespace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNamespace(String value) {
            this.namespace = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the dvNamespace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDvNamespace() {
            return dvNamespace;
        }

        /**
         * Sets the value of the dvNamespace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDvNamespace(String value) {
            this.dvNamespace = value;
        }

        /**
         * Gets the value of the dvName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDvName() {
            return dvName;
        }

        /**
         * Sets the value of the dvName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDvName(String value) {
            this.dvName = value;
        }

        /**
         * Gets the value of the dvVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDvVersion() {
            return dvVersion;
        }

        /**
         * Sets the value of the dvVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDvVersion(String value) {
            this.dvVersion = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the runtime property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRuntime() {
            return runtime;
        }

        /**
         * Sets the value of the runtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRuntime(BigDecimal value) {
            this.runtime = value;
        }

        /**
         * Gets the value of the level property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLevel(BigInteger value) {
            this.level = value;
        }

        /**
         * Gets the value of the compound property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the compound property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompound().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCompound() {
            if (compound == null) {
                compound = new ArrayList<String>();
            }
            return this.compound;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
         *         &lt;element name="filename" type="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Argument {

            @XmlElementRef(name = "filename", namespace = "http://pegasus.isi.edu/schema/DAX", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link PlainFilenameType }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
         *         &lt;element name="filename" type="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="namespace" use="required" type="{http://pegasus.isi.edu/schema/DAX}ProfileNamespace" /&gt;
         *       &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" default="vdl" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Profile {

            @XmlElementRef(name = "filename", namespace = "http://pegasus.isi.edu/schema/DAX", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;
            @XmlAttribute(name = "key", required = true)
            protected String key;
            @XmlAttribute(name = "namespace", required = true)
            protected ProfileNamespace namespace;
            @XmlAttribute(name = "origin")
            protected String origin;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link PlainFilenameType }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the namespace property.
             * 
             * @return
             *     possible object is
             *     {@link ProfileNamespace }
             *     
             */
            public ProfileNamespace getNamespace() {
                return namespace;
            }

            /**
             * Sets the value of the namespace property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProfileNamespace }
             *     
             */
            public void setNamespace(ProfileNamespace value) {
                this.namespace = value;
            }

            /**
             * Gets the value of the origin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrigin() {
                if (origin == null) {
                    return "vdl";
                } else {
                    return origin;
                }
            }

            /**
             * Sets the value of the origin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrigin(String value) {
                this.origin = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
         *       &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="output" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Stderr
            extends StdioType
        {

            @XmlAttribute(name = "link")
            protected LinkageType link;

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link LinkageType }
             *     
             */
            public LinkageType getLink() {
                if (link == null) {
                    return LinkageType.OUTPUT;
                } else {
                    return link;
                }
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link LinkageType }
             *     
             */
            public void setLink(LinkageType value) {
                this.link = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
         *       &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="input" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Stdin
            extends StdioType
        {

            @XmlAttribute(name = "link")
            protected LinkageType link;

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link LinkageType }
             *     
             */
            public LinkageType getLink() {
                if (link == null) {
                    return LinkageType.INPUT;
                } else {
                    return link;
                }
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link LinkageType }
             *     
             */
            public void setLink(LinkageType value) {
                this.link = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://pegasus.isi.edu/schema/DAX}StdioType"&gt;
         *       &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" fixed="output" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Stdout
            extends StdioType
        {

            @XmlAttribute(name = "link")
            protected LinkageType link;

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link LinkageType }
             *     
             */
            public LinkageType getLink() {
                if (link == null) {
                    return LinkageType.OUTPUT;
                } else {
                    return link;
                }
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link LinkageType }
             *     
             */
            public void setLink(LinkageType value) {
                this.link = value;
            }

        }
        
        
        @Override
        public String toString() { 
            return "{[Id: '" + this.id + "'], [Namespace: '" + this.namespace + "'], [Name: '" + this.name + "'], [Version: '" + this.version + "'], [Runtime: '" + this.runtime + "'], [FileList: '" + this.getUses().size() + "']}";
        } 

    }
    
    @Override
    public String toString() { 
        return "{[Name: '" + this.name + "'], [Job Count: '" + this.job.size() + "'], [Child Count: '" + this.child.size() + "']}";
    } 
    
}
