//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.12 at 01:59:25 PM ICT 
//


package com.kmutt.sit.pegasus.xsd.element;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * logical filename representation.
 * 
 * <p>Java class for FilenameType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilenameType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pegasus.isi.edu/schema/DAX}PlainFilenameType"&gt;
 *       &lt;attribute name="temporaryHint" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="link" type="{http://pegasus.isi.edu/schema/DAX}LinkageType" /&gt;
 *       &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="transfer" type="{http://pegasus.isi.edu/schema/DAX}TransferType" default="true" /&gt;
 *       &lt;attribute name="type" type="{http://pegasus.isi.edu/schema/DAX}FileType" default="data" /&gt;
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilenameType")
public class FilenameType
    extends PlainFilenameType
{

    @XmlAttribute(name = "temporaryHint")
    protected String temporaryHint;
    @XmlAttribute(name = "link")
    protected LinkageType link;
    @XmlAttribute(name = "optional")
    protected Boolean optional;
    @XmlAttribute(name = "register")
    protected Boolean register;
    @XmlAttribute(name = "transfer")
    protected TransferType transfer;
    @XmlAttribute(name = "type")
    protected FileType type;
    @XmlAttribute(name = "size")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger size;
    
    public String toString() { 
        return "{[File: '" + this.file + "'], [Link: '" + this.link + "'], [Register: '" + this.register + "'], [Transfer: '" + this.transfer + "'], [Type: '" + this.type + "'], [Size: '" + this.size  + "']}";
    } 

    /**
     * Gets the value of the temporaryHint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporaryHint() {
        return temporaryHint;
    }

    /**
     * Sets the value of the temporaryHint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporaryHint(String value) {
        this.temporaryHint = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link LinkageType }
     *     
     */
    public LinkageType getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkageType }
     *     
     */
    public void setLink(LinkageType value) {
        this.link = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOptional() {
        if (optional == null) {
            return false;
        } else {
            return optional;
        }
    }

    /**
     * Sets the value of the optional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptional(Boolean value) {
        this.optional = value;
    }

    /**
     * Gets the value of the register property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRegister() {
        if (register == null) {
            return true;
        } else {
            return register;
        }
    }

    /**
     * Sets the value of the register property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegister(Boolean value) {
        this.register = value;
    }

    /**
     * Gets the value of the transfer property.
     * 
     * @return
     *     possible object is
     *     {@link TransferType }
     *     
     */
    public TransferType getTransfer() {
        if (transfer == null) {
            return TransferType.TRUE;
        } else {
            return transfer;
        }
    }

    /**
     * Sets the value of the transfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferType }
     *     
     */
    public void setTransfer(TransferType value) {
        this.transfer = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getType() {
        if (type == null) {
            return FileType.DATA;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setType(FileType value) {
        this.type = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

}
