//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.12 at 01:59:25 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pegasus.isi.edu/schema/DAX", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kmutt.sit.pegasus.xsd.element;
