//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.12 at 01:59:25 PM ICT 
//


package com.kmutt.sit.pegasus.xsd.element;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProfileNamespace.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProfileNamespace"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="pegasus"/&gt;
 *     &lt;enumeration value="condor"/&gt;
 *     &lt;enumeration value="dagman"/&gt;
 *     &lt;enumeration value="env"/&gt;
 *     &lt;enumeration value="hints"/&gt;
 *     &lt;enumeration value="globus"/&gt;
 *     &lt;enumeration value="selector"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ProfileNamespace")
@XmlEnum
public enum ProfileNamespace {

    @XmlEnumValue("pegasus")
    PEGASUS("pegasus"),
    @XmlEnumValue("condor")
    CONDOR("condor"),
    @XmlEnumValue("dagman")
    DAGMAN("dagman"),
    @XmlEnumValue("env")
    ENV("env"),
    @XmlEnumValue("hints")
    HINTS("hints"),
    @XmlEnumValue("globus")
    GLOBUS("globus"),
    @XmlEnumValue("selector")
    SELECTOR("selector");
    private final String value;

    ProfileNamespace(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProfileNamespace fromValue(String v) {
        for (ProfileNamespace c: ProfileNamespace.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
