//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.12 at 01:59:25 PM ICT 
//


package com.kmutt.sit.pegasus.xsd.element;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransferType.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransferType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="false"/&gt;
 *     &lt;enumeration value="optional"/&gt;
 *     &lt;enumeration value="true"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TransferType")
@XmlEnum
public enum TransferType {

    @XmlEnumValue("false")
    FALSE("false"),
    @XmlEnumValue("optional")
    OPTIONAL("optional"),
    @XmlEnumValue("true")
    TRUE("true");
    private final String value;

    TransferType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransferType fromValue(String v) {
        for (TransferType c: TransferType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
